---
name: behave

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shipwright-tests:
    name: Shipwright System Testing
    runs-on: ubuntu-latest
    steps:
      - uses: helm/kind-action@v1.2.0
        with:
          version: v0.14.0
          cluster_name: kind
          wait: 120s

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: imjasonh/setup-ko@v0.6
      - uses: shipwright-io/setup@main
        with:
          version: tip

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: actions/checkout@v3

      - name: Install Test Dependencies
        run: |
          make pip-install

      - name: Unit Tests
        run: |
          make test

      - name: Shipwright System Tests
        run: |
          make behave